/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyecto.gym;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SONY
 */
 
public class Asistencia extends javax.swing.JInternalFrame {
    DefaultTableModel tabla=new DefaultTableModel();
    int i,r;
    int contador;
    String fecha,pago,id;
        Conexion obj=new Conexion();
        //Declarar objetos de conexion
        Connection Conexion;
        //Realizar el lenguaje sql
        PreparedStatement Consulta;
        //Almacena los datos de nuestra consulta
        ResultSet Datos;
        String nom,Id;
    /**
     * Creates new form Asistencia
     */
    public Asistencia() {
        initComponents();
        tabla.addColumn("Nombre Completo");
        tabla.addColumn("Id");                
        tabla.addColumn("Edad"); 
        tabla.addColumn("Sexo");        
        this.jtablaUsuarios.setModel(tabla);        
    }
    public void conectar()
     {
         Conexion =(Connection) obj.getConnection("java","root","9013113479");
     }
     public void desconectar()
     {
         try {
            Conexion.close();
            Consulta.close();
            Datos=null;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
     }
    public void AbilitaDesab(boolean res)
    {
        rdbtnSi.setEnabled(res);
        rdbtnNo.setEnabled(res);
    }
    public void Desabilitar()
    {
        rdbtnSi.setEnabled(false);
        rdbtnNo.setEnabled(false);
        chAsistio.setEnabled(false);
        btnGuardar.setEnabled(false);
        chAsistio.setSelected(false);
        txtFecha.setText("");
        txtNombre.setText("");
        txtNombre.requestFocus();
    }
    public void limpiarTabla()
    {
        int b=0;        
        while(b<=(i-1))
        {
            if(tabla.getRowCount()!=0)
            tabla.removeRow(0);//borrar lo que contiene la tabla del panel de consulta
            b+=1;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupPago = new javax.swing.ButtonGroup();
        txtNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        ListaId = new java.awt.List();
        txtFecha = new javax.swing.JTextField();
        chAsistio = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        rdbtnSi = new javax.swing.JRadioButton();
        rdbtnNo = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtablaUsuarios = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        txtNombre.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.setText("Ingrese Nombre");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        ListaId.setVisible(false);

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N

        chAsistio.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        chAsistio.setText("Asistio");
        chAsistio.setAutoscrolls(true);
        chAsistio.setEnabled(false);
        chAsistio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chAsistioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel1.setText("Pago");

        btnGrupPago.add(rdbtnSi);
        rdbtnSi.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        rdbtnSi.setText("Si");
        rdbtnSi.setEnabled(false);

        btnGrupPago.add(rdbtnNo);
        rdbtnNo.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        rdbtnNo.setSelected(true);
        rdbtnNo.setText("No");
        rdbtnNo.setEnabled(false);

        jtablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtablaUsuarios);

        btnGuardar.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jScrollPane2)
                .addGap(91, 91, 91)
                .addComponent(ListaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbtnSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbtnNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chAsistio))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)))
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(276, 276, 276))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(ListaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chAsistio)
                    .addComponent(rdbtnSi)
                    .addComponent(rdbtnNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        limpiarTabla();
        ListaId.clear();
        i=0;
        String res[]=new String[4];
        nom=txtNombre.getText().toUpperCase();
        try {
            conectar();
            Consulta=Conexion.prepareStatement("SELECT * FROM java.usuarios WHERE Nombre LIKE \""+nom+"%\"");
            Datos=Consulta.executeQuery();
            while(Datos.next())
            {
                res[0]=Datos.getString("Nombre")+" "+Datos.getString("Apellido");
                res[1]=Datos.getString("Id");
                res[2]=Datos.getString("Edad");
                res[3]=Datos.getString("Sexo");                
                tabla.addRow(res);
                ListaId.add(Datos.getString("Id"));
                i+=1;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e,"Error Conexion",JOptionPane.ERROR_MESSAGE);
        }finally
        {
            desconectar();
        }
        if(i==0)
        {
            JOptionPane.showMessageDialog(null,"Nombre No Encontrado",null,JOptionPane.INFORMATION_MESSAGE);
            Desabilitar();
        }
    }//GEN-LAST:event_btnBuscarActionPerformed
    private void chAsistioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chAsistioActionPerformed
       if(chAsistio.isSelected())
       {
           fecha=obj.select("current_date as","año");
           txtFecha.setText(fecha); 
           btnGuardar.setEnabled(true);
       }
       else
       {
           txtFecha.setText("");
           btnGuardar.setEnabled(false);
       }
    }//GEN-LAST:event_chAsistioActionPerformed
    private void jtablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaUsuariosMouseClicked
        contador=0; 
        r=0;
        id="";
        id=ListaId.getItem(jtablaUsuarios.getSelectedRow());             
        if(jtablaUsuarios.getRowCount()>0)
        {
            chAsistio.setEnabled(true);
            rdbtnNo.setSelected(true);
            AbilitaDesab(true);            
            try 
            {
                conectar();
                Consulta=Conexion.prepareStatement("SELECT * FROM java.mensualidad WHERE Usu_men_id ="+id);
                Datos=Consulta.executeQuery();
                while(Datos.next())
                {
                    contador=Integer.parseInt(Datos.getString("Contador"));
                    r=1;
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e,"Error Conexion",JOptionPane.ERROR_MESSAGE);
            }finally
            {
                desconectar();
            }
        }
        if(r==1)
        {
            rdbtnSi.setSelected(true);
            AbilitaDesab(false);
        }
        
    }//GEN-LAST:event_jtablaUsuariosMouseClicked
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(rdbtnSi.isSelected())
            pago=rdbtnSi.getLabel();
        else
           pago=rdbtnNo.getLabel();
        id=ListaId.getItem(jtablaUsuarios.getSelectedRow());
        fecha=txtFecha.getText();
        boolean resp=obj.addAsistencia(id, fecha, pago);
        if(r==1 && resp==true)
        {
            contador-=1;
            try {
            conectar();
            String Query="UPDATE mensualidad SET Contador = "+contador+" WHERE Usu_men_id =\""+id+"\"";
            Statement st= Conexion.createStatement();
            st.executeUpdate(Query);
        } catch (SQLException e) {
            if(e.toString().contains("Duplicate entry"))            
                JOptionPane.showMessageDialog(null,"Ya Existe un Usuario Con El Mismo N° Id",null,JOptionPane.WARNING_MESSAGE);                 
            else
                JOptionPane.showMessageDialog(null, e,"Error Conexion",JOptionPane.ERROR_MESSAGE);            
        }finally{
                desconectar();
            }
        }
        Desabilitar();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        txtNombre.setForeground(Color.BLACK);
        txtNombre.setText("");
    }//GEN-LAST:event_txtNombreMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List ListaId;
    private javax.swing.JButton btnBuscar;
    private javax.swing.ButtonGroup btnGrupPago;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chAsistio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtablaUsuarios;
    private javax.swing.JRadioButton rdbtnNo;
    private javax.swing.JRadioButton rdbtnSi;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
