package proyecto.gym;
public class pantalla extends javax.swing.JFrame {

    /**
     * Creates new form pantalla
     */
    Conexion conec=new Conexion();
    String N="",A="";
    public void UsuarioAcceso(String nom,String ape)
    {
        N=nom;
        A=ape;
    }
    public pantalla() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JDesktopPane();
        lbFecha = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemNuevoU = new javax.swing.JMenuItem();
        MenuItemConsultaU = new javax.swing.JMenuItem();
        MenuItemEliminarU = new javax.swing.JMenuItem();
        MenuItemActualizarU = new javax.swing.JMenuItem();
        MenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItemAsistencia = new javax.swing.JMenuItem();
        MenuItemMensualidad = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbFecha.setBackground(new java.awt.Color(0, 0, 0));
        lbFecha.setFont(new java.awt.Font("Baskerville Old Face", 1, 20)); // NOI18N
        lbFecha.setForeground(new java.awt.Color(255, 255, 255));
        lbFecha.setText("Fecha");
        lbFecha.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                lbFechaHierarchyChanged(evt);
            }
        });

        lbUsuario.setBackground(new java.awt.Color(0, 0, 0));
        lbUsuario.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuario.setText("UAcceso");
        lbUsuario.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                lbUsuarioHierarchyChanged(evt);
            }
        });

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 506, Short.MAX_VALUE)
                .addComponent(lbFecha)
                .addContainerGap())
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorLayout.createSequentialGroup()
                .addGap(0, 359, Short.MAX_VALUE)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFecha)
                    .addComponent(lbUsuario))
                .addContainerGap())
        );
        Contenedor.setLayer(lbFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Contenedor.setLayer(lbUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("Menú");

        MenuItemNuevoU.setText("Nuevo Usuario");
        MenuItemNuevoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNuevoUActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemNuevoU);

        MenuItemConsultaU.setText("Consultar Usuarios");
        MenuItemConsultaU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemConsultaUActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemConsultaU);

        MenuItemEliminarU.setText("Eliminar Usuario");
        MenuItemEliminarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEliminarUActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemEliminarU);

        MenuItemActualizarU.setText("Actualizar Usuario");
        MenuItemActualizarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActualizarUActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemActualizarU);

        MenuItemSalir.setText("Salir");
        MenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opcion");

        MenuItemAsistencia.setText("Asistencia");
        MenuItemAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAsistenciaActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemAsistencia);

        MenuItemMensualidad.setText("Mensualidad");
        MenuItemMensualidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemMensualidadActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemMensualidad);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSalirActionPerformed
        //System.exit(WIDTH); // salir por completo del sistema
        Acceso inicio=new Acceso();
        inicio.show();
        this.hide();
    }//GEN-LAST:event_MenuItemSalirActionPerformed

    private void lbFechaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_lbFechaHierarchyChanged
        lbFecha.setText(conec.select("current_date as","año"));    
        lbUsuario.setText(N+" "+A);
    }//GEN-LAST:event_lbFechaHierarchyChanged

    private void MenuItemNuevoUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNuevoUActionPerformed
       Nuevo_Usuario user=new Nuevo_Usuario();
       Contenedor.add(user);
       user.show();
    }//GEN-LAST:event_MenuItemNuevoUActionPerformed

    private void MenuItemConsultaUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemConsultaUActionPerformed
        Consultar_Usuario consulta=new Consultar_Usuario();
        Contenedor.add(consulta);
        consulta.show();
    }//GEN-LAST:event_MenuItemConsultaUActionPerformed

    private void MenuItemEliminarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEliminarUActionPerformed
        Eliminar_Usuario eliminar=new Eliminar_Usuario();       
        Contenedor.add(eliminar);
        eliminar.show();          
        
    }//GEN-LAST:event_MenuItemEliminarUActionPerformed

    private void MenuItemActualizarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActualizarUActionPerformed
        Actualizar_Usuario actualizar=new Actualizar_Usuario();
        Contenedor.add(actualizar);
        actualizar.show();
    }//GEN-LAST:event_MenuItemActualizarUActionPerformed

    private void MenuItemAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAsistenciaActionPerformed
        Asistencia asistencia=new Asistencia();
        Contenedor.add(asistencia);
        asistencia.show();
    }//GEN-LAST:event_MenuItemAsistenciaActionPerformed

    private void MenuItemMensualidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemMensualidadActionPerformed
        Mensualidad mensualidad=new Mensualidad();
        Contenedor.add(mensualidad);
        mensualidad.show();
    }//GEN-LAST:event_MenuItemMensualidadActionPerformed

    private void lbUsuarioHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_lbUsuarioHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lbUsuarioHierarchyChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane Contenedor;
    private javax.swing.JMenuItem MenuItemActualizarU;
    private javax.swing.JMenuItem MenuItemAsistencia;
    private javax.swing.JMenuItem MenuItemConsultaU;
    private javax.swing.JMenuItem MenuItemEliminarU;
    private javax.swing.JMenuItem MenuItemMensualidad;
    private javax.swing.JMenuItem MenuItemNuevoU;
    private javax.swing.JMenuItem MenuItemSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbUsuario;
    // End of variables declaration//GEN-END:variables
}
