/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyecto.gym;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SONY
 */
public class ventana extends javax.swing.JFrame {
    /**
     * Creates new form ventana
     */
    DefaultTableModel tabla;
    DefaultListModel lista=new DefaultListModel();
    public ventana() {     
        initComponents();
        tabla =new DefaultTableModel();
        tabla.addColumn("Id");
        tabla.addColumn("Nombre");
        tabla.addColumn("Apellido");
        tabla.addColumn("Edad"); 
        tabla.addColumn("Sexo"); 
        tabla.addColumn("Peso");
        tabla.addColumn("Fecha Inicio");
        this.jTable1.setModel(tabla);   
        this.jNombre.setModel(lista);
        txtNom.requestFocus();        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */  
    Conexion obj=new Conexion();
    String nom,ape,cont,cont2,Id,edad,sexo;
    int peso,dia,mes,año;
    int i=0;
    //Declarar objetos de conexion
        Connection Conexion;
        //Realizar el lenguaje sql
        PreparedStatement consulta;
        //Almacena los datos de nuestra consulta
        ResultSet datos;
    String date[]=new String[6];
    @SuppressWarnings("unchecked")
    public void Limpiar()//limpiar caja de texto panel registro
    {
        txtNom.setText("");
        txtApe.setText("");
        txtId.setText("");
        txtNom.requestFocus();
    }
    public void LimpiarActualizacion()
    {
        txtAIdBuscar.setEnabled(true);
        btnABuscar.setEnabled(true);                
        btnActualizar.setEnabled(false);
        txtANombre.setEnabled(false);
        txtAApellido.setEnabled(false);
        txtAId.setEnabled(false);
        txtAEdad.setEnabled(false);
        txtAFecha.setEnabled(false);
        txtAPeso.setEnabled(false);
        txtASexo.setEnabled(false);
    }
    public void LimpiarTablaCons()
    {
        
        int b=0;        
        while(b<=(i-1))
        {
            if(tabla.getRowCount()!=0)
            tabla.removeRow(0);//borrar lo que contiene la tabla del panel de consulta
            b+=1;
        }        
        btnConsul.setEnabled(true);
    }
    public void limpiarListaEliminar()
    {
        listaId.clear();//Limpiar la lista que esta oculta
        lista.clear();//Limpiar la lista que se muestra
    }
    public void Validar(java.awt.event.KeyEvent evt)//validacion solo numeros
    {
        String le= String.valueOf(evt.getKeyChar());

        if (le.matches("[a-zA-Z]"))//Validar solo los Numeros
        {
            evt.consume();//Le decimos que no los muestre
            getToolkit().beep();//Utilizamos para hacer escuchar un sonido
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnGrupSexualidad = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApe = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SpnDia = new javax.swing.JSpinner();
        SpnEdad = new javax.swing.JSpinner();
        SpnPeso = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        cbxMes = new javax.swing.JComboBox();
        spnAño = new javax.swing.JSpinner();
        rdbtnMas = new javax.swing.JRadioButton();
        rdbtnFem = new javax.swing.JRadioButton();
        lbFecha = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnConsul = new javax.swing.JButton();
        txtBusNom = new javax.swing.JTextField();
        btnConsuLimpiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtAIdBuscar = new javax.swing.JTextField();
        btnABuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtANombre = new javax.swing.JTextField();
        txtAApellido = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAEdad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAPeso = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtAFecha = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtASexo = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnALimpiar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtAId = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnElimiBuscar = new javax.swing.JButton();
        listaId = new java.awt.List();
        btnEliminar = new javax.swing.JButton();
        txtEliNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jNombre = new javax.swing.JList();

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel5.setText("Bienvenido");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTabbedPane1HierarchyChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel2.setText("Nombres");

        txtNom.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel3.setText("Apellidos");

        txtApe.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnGuardarStateChanged(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel7.setText("N° id:");

        txtId.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel8.setText("Edad");

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel9.setText("Peso");

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel10.setText("Fecha Inicio");

        SpnDia.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        SpnDia.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        SpnEdad.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        SpnEdad.setModel(new javax.swing.SpinnerNumberModel(10, 10, 80, 1));

        SpnPeso.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        SpnPeso.setModel(new javax.swing.SpinnerNumberModel(20, 20, 250, 1));

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        jLabel11.setText("Kg");

        cbxMes.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        cbxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        spnAño.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        spnAño.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2014), Integer.valueOf(2014), null, Integer.valueOf(1)));

        btnGrupSexualidad.add(rdbtnMas);
        rdbtnMas.setSelected(true);
        rdbtnMas.setText("Masculino");

        btnGrupSexualidad.add(rdbtnFem);
        rdbtnFem.setText("Femenino");

        lbFecha.setText("jLabel1");
        lbFecha.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                lbFechaHierarchyChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar))
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApe, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SpnPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SpnDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SpnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(rdbtnMas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnFem)))
                .addContainerGap(179, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbFecha)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFecha)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(SpnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtnMas)
                    .addComponent(rdbtnFem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(SpnPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(SpnDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnGuardar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro", jPanel1);

        jPanel2.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel2HierarchyChanged(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnConsul.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnConsul.setText("Consultar");
        btnConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulActionPerformed(evt);
            }
        });

        txtBusNom.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        txtBusNom.setForeground(new java.awt.Color(204, 204, 204));
        txtBusNom.setText("Ingrese Nombre");
        txtBusNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBusNomMouseClicked(evt);
            }
        });

        btnConsuLimpiar.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnConsuLimpiar.setText("Limpiar");
        btnConsuLimpiar.setEnabled(false);
        btnConsuLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsuLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(txtBusNom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsuLimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsul)
                    .addComponent(txtBusNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsuLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel4.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel4HierarchyChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel4.setText("N° ID");

        txtAIdBuscar.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        txtAIdBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAIdBuscarKeyTyped(evt);
            }
        });

        btnABuscar.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnABuscar.setText("Buscar");
        btnABuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnABuscarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel6.setText("Nombres");

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel12.setText("Apellidos");

        txtANombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtANombre.setEnabled(false);
        txtANombre.setMinimumSize(new java.awt.Dimension(6, 25));
        txtANombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtANombreMouseClicked(evt);
            }
        });
        txtANombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtANombreKeyTyped(evt);
            }
        });

        txtAApellido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAApellido.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel13.setText("Edad");

        txtAEdad.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        txtAEdad.setEnabled(false);
        txtAEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAEdadKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel14.setText("Peso");

        txtAPeso.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        txtAPeso.setEnabled(false);
        txtAPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAPesoKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel15.setText("Fecha Inicio");

        txtAFecha.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        txtAFecha.setEnabled(false);
        txtAFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAFechaKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel16.setText("Sexo");

        txtASexo.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        txtASexo.setEnabled(false);
        txtASexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtASexoKeyTyped(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnALimpiar.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        btnALimpiar.setText("Limpiar");
        btnALimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALimpiarActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel17.setText("Id");

        txtAId.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        txtAId.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtAFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtANombre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtASexo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnActualizar))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnABuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnALimpiar)))
                        .addGap(71, 71, 71))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAId, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnABuscar)
                    .addComponent(jLabel4)
                    .addComponent(btnALimpiar))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtANombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtAId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtAApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtAEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtAFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtASexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actualizar", jPanel4);

        jPanel5.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jPanel5HierarchyChanged(evt);
            }
        });

        btnElimiBuscar.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btnElimiBuscar.setText("Buscar");
        btnElimiBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimiBuscarActionPerformed(evt);
            }
        });

        listaId.setVisible(false);

        btnEliminar.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtEliNombre.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        txtEliNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtEliNombre.setText("Ingrese Nombre");
        txtEliNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEliNombreMouseClicked(evt);
            }
        });

        jNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNombreMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jNombre);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(txtEliNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnElimiBuscar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btnEliminar)
                                .addGap(69, 69, 69)))
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)))
                .addComponent(listaId, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnElimiBuscar)
                    .addComponent(txtEliNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(listaId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTabbedPane1HierarchyChanged

    }//GEN-LAST:event_jTabbedPane1HierarchyChanged

    private void jNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNombreMouseClicked
        if(jNombre.getLastVisibleIndex()==-1)
        {
            btnEliminar.setEnabled(false);
        }else
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_jNombreMouseClicked

    private void txtEliNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliNombreMouseClicked
        txtEliNombre.setText("");
        txtEliNombre.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtEliNombreMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(jNombre.getSelectedIndex()<0)
        {
            JOptionPane.showMessageDialog(null,"Seleccione Uno Para Eliminarlo",null,JOptionPane.INFORMATION_MESSAGE);
        }else{
            OpcEliminar.setVisible(true);
            OpcEliminar.setLocationRelativeTo(null);
            this.setVisible(false);
            Id=listaId.getItem(jNombre.getSelectedIndex());
            nom=String.valueOf(jNombre.getSelectedValue());
            OpcEliminar.EliminarDato(Id, nom);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnElimiBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimiBuscarActionPerformed
        limpiarListaEliminar();
        i=0;
        nom=txtEliNombre.getText().toUpperCase();
        try {
            Conexion =(Connection) obj.getConnection("java","root","9013113479");
            consulta=Conexion.prepareStatement("SELECT * FROM java.usuarios WHERE Nombre LIKE \""+nom+"%\"");
            datos=consulta.executeQuery();
            while(datos.next())
            {

                lista.addElement(datos.getString("Nombre")+" "+datos.getString("Apellido"));
                listaId.add(datos.getString("Id"));
                i+=1;

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e,"Error Conexion",JOptionPane.ERROR_MESSAGE);
        }finally
        {
            try {
                obj.Conexion.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex,"Error Conexion",JOptionPane.ERROR_MESSAGE);
            }
        }
        if(i==0)
        {
            JOptionPane.showMessageDialog(null,"Nombre No Encontrado",null,JOptionPane.INFORMATION_MESSAGE);
            btnEliminar.setEnabled(false);
        }
        txtEliNombre.setText("Ingrese Nombre");
        txtEliNombre.setForeground(Color.GRAY);
    }//GEN-LAST:event_btnElimiBuscarActionPerformed

    private void btnALimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALimpiarActionPerformed
        LimpiarActualizacion();
        txtANombre.setText("");
        txtAApellido.setText("");
        txtAId.setText("");
        txtAEdad.setText("");
        txtAFecha.setText("");
        txtAPeso.setText("");
        txtASexo.setText("");
        txtAIdBuscar.setText("");
        txtAIdBuscar.requestFocus();
    }//GEN-LAST:event_btnALimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String fecha;
        nom=txtANombre.getText().toUpperCase();
        ape=txtAApellido.getText().toUpperCase();
        Id=txtAId.getText();
        edad=txtAEdad.getText();
        peso=Integer.parseInt(txtAPeso.getText());
        sexo=txtASexo.getText().toUpperCase();
        fecha=txtAFecha.getText();
        try {
            Conexion =(Connection) obj.getConnection("java","root","9013113479");
            String Query="UPDATE usuarios SET Id = \""+Id+"\", Nombre = \""+nom+"\", Apellido = \""+
            ape+"\", Edad = \""+edad+"\", Sexo = \""+sexo+"\", Edad = "+edad+
            ", Fech = \""+fecha+"\" WHERE Id =\""+txtAIdBuscar.getText()+"\"";
            Statement st= Conexion.createStatement();
            st.executeUpdate(Query);
            JOptionPane.showMessageDialog(null,"Datos Actualizados",null,JOptionPane.INFORMATION_MESSAGE);
            LimpiarActualizacion();
            Conexion.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e,"Error Conexion",JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtASexoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtASexoKeyTyped
        String le= String.valueOf(evt.getKeyChar());
        if(txtASexo.getText().length()>=1)
        {
            evt.consume();//Le decimos que no los muestre
            getToolkit().beep();
        }
        if (le.matches("[MmfF]"))//Validar solo los Numeros
        {}
        else
        {
            evt.consume();//Le decimos que no los muestre
            getToolkit().beep();//Utilizamos para hacer escuchar un sonido
        }
    }//GEN-LAST:event_txtASexoKeyTyped

    private void txtAFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAFechaKeyTyped
        Validar(evt);
        if(txtAFecha.getText().length()>=10)
        {
            evt.consume();//Le decimos que no los muestre
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtAFechaKeyTyped

    private void txtAPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAPesoKeyTyped
        Validar(evt);
        if(txtAPeso.getText().length()>=3)
        {
            evt.consume();//Le decimos que no los muestre
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtAPesoKeyTyped

    private void txtAEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAEdadKeyTyped
        Validar(evt);
        if(txtAEdad.getText().length()>=3)
        {
            evt.consume();//Le decimos que no los muestre
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtAEdadKeyTyped

    private void txtANombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtANombreKeyTyped

    }//GEN-LAST:event_txtANombreKeyTyped

    private void txtANombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtANombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtANombreMouseClicked

    private void btnABuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnABuscarActionPerformed
        i=0;
        String res[]=new String[7];
        String id=txtAIdBuscar.getText();
        try {
            Conexion =(Connection) obj.getConnection("java","root","9013113479");
            consulta=Conexion.prepareStatement("SELECT * FROM java.usuarios WHERE Id LIKE \""+id+"\"");
            datos=consulta.executeQuery();
            while(datos.next()){
                res[0]=datos.getString("Id");
                txtAId.setText(res[0]);
                res[1]=datos.getString("Nombre");
                txtANombre.setText(res[1]);
                res[2]=datos.getString("Apellido");
                txtAApellido.setText(res[2]);
                res[3]=datos.getString("Edad");
                txtAEdad.setText(res[3]);
                res[4]=datos.getString("Sexo");
                txtASexo.setText(res[4]);
                res[5]=datos.getString("Peso");
                txtAPeso.setText(res[5]);
                res[6]=datos.getString("Fech");
                txtAFecha.setText(res[6]);
                txtAIdBuscar.setEnabled(false);
                btnABuscar.setEnabled(false);
                btnActualizar.setEnabled(true);
                txtANombre.setEnabled(true);
                txtAApellido.setEnabled(true);
                txtAId.setEnabled(true);
                txtAEdad.setEnabled(true);
                txtAFecha.setEnabled(true);
                txtAPeso.setEnabled(true);
                txtASexo.setEnabled(true);
                i=1;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e,"Error Conexion",JOptionPane.PLAIN_MESSAGE);
        }finally
        {
            try {
                obj.Conexion.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex,"Error Conexion",JOptionPane.PLAIN_MESSAGE);
            }
        }
        if(i==0)
        {
            JOptionPane.showMessageDialog(null,"No Se Encontro Informacion  ","Error",JOptionPane.YES_OPTION);
        }
        txtAIdBuscar.requestFocus();
    }//GEN-LAST:event_btnABuscarActionPerformed

    private void txtAIdBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAIdBuscarKeyTyped
        Validar(evt);//valoidar solo numeros
    }//GEN-LAST:event_txtAIdBuscarKeyTyped

    private void jPanel2HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel2HierarchyChanged
        //cada vez que cambie de de tab me limpie el tab de consultas
        LimpiarTablaCons();
        btnConsuLimpiar.setEnabled(false);
    }//GEN-LAST:event_jPanel2HierarchyChanged

    private void btnConsuLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsuLimpiarActionPerformed
        LimpiarTablaCons();
        btnConsuLimpiar.setEnabled(false);
    }//GEN-LAST:event_btnConsuLimpiarActionPerformed

    private void txtBusNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBusNomMouseClicked
        txtBusNom.setText("");
        txtBusNom.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusNomMouseClicked

    private void btnConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulActionPerformed

        String res[]=new String[7];
        i=0;
        nom=txtBusNom.getText().toUpperCase();
        try {
            Conexion =(Connection) obj.getConnection("java","root","9013113479");
            consulta=Conexion.prepareStatement("SELECT * FROM java.usuarios WHERE Nombre LIKE \""+nom+"%\"");
            datos=consulta.executeQuery();
            while(datos.next())
            {
                res[0]=datos.getString("Id");
                res[1]=datos.getString("Nombre");
                res[2]=datos.getString("Apellido");
                res[3]=datos.getString("Edad");
                res[4]=datos.getString("Sexo");
                res[5]=datos.getString("Peso");
                res[6]=datos.getString("Fech");
                tabla.addRow(res);
                i+=1;
                btnConsuLimpiar.setEnabled(true);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e,"Error Conexion",JOptionPane.ERROR_MESSAGE);
        }finally
        {
            try {
                obj.Conexion.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex,"Error Conexion",JOptionPane.ERROR_MESSAGE);
            }
        }
        if(i==0)
        {
            btnConsul.setEnabled(true);
            JOptionPane.showMessageDialog(null,"Nombre No Encontrado",null,JOptionPane.INFORMATION_MESSAGE);
            txtBusNom.setText("Ingrese Nombre");
            txtBusNom.setForeground(Color.GRAY);
        }
        else{
            btnConsul.setEnabled(false);
            txtBusNom.setText("Ingrese Nombre");
            txtBusNom.setForeground(Color.GRAY);
        }
        System.out.println(i);
    }//GEN-LAST:event_btnConsulActionPerformed

    private void lbFechaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_lbFechaHierarchyChanged
        lbFecha.setText(obj.select("current_date as","año"));        // colocar en el label la fecha con año-mes-día
    }//GEN-LAST:event_lbFechaHierarchyChanged

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar();//borrar datos de la caja de texto del panel registro
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        Validar(evt);//validar solo numeros
    }//GEN-LAST:event_txtIdKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (String.valueOf(txtNom.getText()).compareTo("")==0||String.valueOf(txtApe.getText()).compareTo("")==0
            || String.valueOf(txtId.getText()).compareTo("")==0  )
        {
            JOptionPane.showMessageDialog(null,"Ingrese Datos Completos","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(rdbtnFem.isSelected())
            sexo="F";
            else
            sexo="M";
            nom=txtNom.getText().toUpperCase();
            ape=txtApe.getText().toUpperCase();
            Id=txtId.getText();
            edad=SpnEdad.getValue().toString();
            peso=(int) SpnPeso.getValue();
            año=(int)spnAño.getValue();
            mes=1+(cbxMes.getSelectedIndex());
            dia=(int)SpnDia.getValue();
            String fecha=año+"-"+mes+"-"+dia;
            obj.agregar(nom, ape, Id, edad,sexo, peso, fecha);
            Limpiar();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnGuardarStateChanged

    }//GEN-LAST:event_btnGuardarStateChanged

    private void jPanel4HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel4HierarchyChanged
       LimpiarActualizacion();//borrar datos de la caja de texto del panel de Actualizar
       txtAIdBuscar.setText("");
    }//GEN-LAST:event_jPanel4HierarchyChanged

    private void jPanel5HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jPanel5HierarchyChanged
        limpiarListaEliminar();
        txtEliNombre.setText("Ingrese Nombre");
        txtEliNombre.setForeground(Color.GRAY);
    }//GEN-LAST:event_jPanel5HierarchyChanged

OpcionEliminar OpcEliminar=new OpcionEliminar();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpnDia;
    private javax.swing.JSpinner SpnEdad;
    private javax.swing.JSpinner SpnPeso;
    private javax.swing.JButton btnABuscar;
    private javax.swing.JButton btnALimpiar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsuLimpiar;
    private javax.swing.JButton btnConsul;
    private javax.swing.JButton btnElimiBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.ButtonGroup btnGrupSexualidad;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox cbxMes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbFecha;
    private java.awt.List listaId;
    private javax.swing.JRadioButton rdbtnFem;
    private javax.swing.JRadioButton rdbtnMas;
    private javax.swing.JSpinner spnAño;
    private javax.swing.JTextField txtAApellido;
    private javax.swing.JTextField txtAEdad;
    private javax.swing.JTextField txtAFecha;
    private javax.swing.JTextField txtAId;
    private javax.swing.JTextField txtAIdBuscar;
    private javax.swing.JTextField txtANombre;
    private javax.swing.JTextField txtAPeso;
    private javax.swing.JTextField txtASexo;
    private javax.swing.JTextField txtApe;
    private javax.swing.JTextField txtBusNom;
    private javax.swing.JTextField txtEliNombre;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
